skeleton: adapt init.d files to Buildroot standard

diff --git a/skeleton/etc/init.d/S39wpa_supplicant b/skeleton/etc/init.d/S39wpa_supplicant
--- a/skeleton/etc/init.d/S39wpa_supplicant
+++ b/skeleton/etc/init.d/S39wpa_supplicant
@@ -3,7 +3,9 @@
 # wpa_supplicant	Starts wireless connection handler.
 #
 
-script=$(basename $0)
+DAEMON=wpa_supplicant
+PIDFILE="/var/run/$DAEMON.pid"
+bin_file=/usr/sbin/wpa_supplicant
 cfg_file="/etc/wpa_supplicant/wpa_supplicant.conf"
 log_file="/var/log/wpa_supplicant.log"
 
@@ -17,21 +19,29 @@ for i in /sys/class/net/wlan?; do
 	config="${config} -i`basename $i` -Dnl80211,wext -c${cfg_file}"
 done
 
+start() {
+	echo -n "Starting $DAEMON... "
+	start-stop-daemon -S -b -m -p $PIDFILE -x /usr/sbin/wpa_supplicant -- -B -f${log_file} ${config}
+	[ ! -z $(pidof $DAEMON) ] && echo "OK" || echo "FAIL"
+}
+
+stop() {
+	echo -n "Stopping $DAEMON... "
+	start-stop-daemon -K -p $PIDFILE
+	[ $? -eq 0 ] && echo "OK" || echo "ERROR"
+}
+
+restart() {
+	stop
+	start
+}
+
 case "$1" in
-  start)
-	echo "$script: Starting wpa_supplicant..."
-	/usr/sbin/wpa_supplicant -B -f${log_file} ${config}
-	;;
-  stop)
-	echo -n "Stopping wpa_supplicant..."
-	kill -9 $(ps -w | grep wpa_supplicant | awk '{print $1; exit}')
-	;;
-  restart)
-	"$0" stop
-	"$0" start
+  start|stop|restart)
+	"$1"
 	;;
   *)
-	echo "Usage: $script {start|stop|restart}"
+	echo "Usage: $0 {start|stop|restart}"
 	exit 1
 esac
 
diff --git a/skeleton/etc/init.d/S95mpd b/skeleton/etc/init.d/S95mpd
--- a/skeleton/etc/init.d/S95mpd
+++ b/skeleton/etc/init.d/S95mpd
@@ -75,43 +75,31 @@ start() {
 	unmute
 	# mpd priority is below default hard interrupt priority (50)
 	ulimit -HS -r 50
-	# mpd needs a pid_file entry in mpd.conf corresponding to $PIDFILE
-	# using the start-stop-daemon --make-pidfile option does not work
+	# mpd creates its own $PIDFILE, do not use --make-pidfile 
 	start-stop-daemon --start --quiet --background --exec /usr/bin/mpd
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
-	return "$status"
+	[ ! -z $(pidof mpd) ] && echo "OK" || echo "FAIL"
 } 
 
 stop() {
 	echo -n "Stopping mpd: "
 	start-stop-daemon --stop --quiet --pidfile $PIDFILE
 	status=$?
-	if [ "$status" -eq 0 ]; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
-	return "$status"
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 } 
 
+restart() {
+	stop
+	sleep 1
+	start
+}
+
 case "$1" in
-	start)
-		start
-		;;
-	stop) 
-		stop
-		;;
-	restart|reload) 
-		stop
-		sleep 1 
-		start
-		;;
-	*)
-		echo "Usage: $0 {start|stop|restart}" 
-		exit 1
+  start|stop|restart)
+	"$1"
+	;;
+  *)
+	echo "Usage: $0 {start|stop|restart}"
+	exit 1
 esac
+
+exit $?
